### ISSUE TITLE
youtube.user.js: support video with encrypted signature

### ISSUE THREAD

**Issue by ghost** [spenibus/greasemonkey-scripts#1]
Example:

https://www.youtube.com/watch?v=MHnVJtw_xcw

**Comment by spenibus** [comment]
That's the one thing I never got around to do in that userscript because it hasn't bothered me past the breaking point. I guess I can always cheat a bit and leverage whatever others have done so far.

Conclusion: no promise because I don't know how much work this involves, but you never know what might happen.

**Comment by ghost** [comment]
My script does work with encrypted videos:

http://github.com/svnpenn/bm/blob/ccd315c/yt-dl/yt-dl.js

However my method is less conventional. The traditional method is to run:

```
ytplayer.config.assets.js
```

Which gives you the URL to the JavaScript HTML5 player. That file contains the signature decryption function.

**Comment by spenibus** [comment]
Fixed with f01f38f74747444157fb582aa5d174bb7e4ad5ab.

It's a little hackish to my taste but it does the job.

**Comment by spenibus** [comment]
Also, for future reference, the video in the original post is not available to me.

I used this one for testing: https://www.youtube.com/watch?v=VU5eR6OJNUc

**Comment by ghost** [comment]
That is funny: the quora link in your commit contains a link to a SuperUser post written by me :hushed:

**Comment by spenibus** [comment]
I made sure to be as lazy as being a programmer would allow me to be and read the least I could get away with. But indeed, I see that now.
